// Auto-generated by scripts/extract_cuda_kernels.py
// This file includes all kernel sources and registers them via pybind11.
//
// Compiled as a single translation unit so all namespaces are visible.

#include "rmsnorm/rmsnorm_kernel.cu"
#include "rope/rope_kernel.cu"
#include "m_rope/m_rope_kernel.cu"
#include "rot_pos/rot_pos.cu"
#include "get_rope_index/get_rope_index.cu"
#include "window_index/window_index.cu"
#include "permute_unpermute/permute.cu"

PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
    m.def("rmsnorm", &tvm_ffi_rmsnorm::RMSNorm);
    m.def("rmsnorm_backward", &tvm_ffi_rmsnorm::RMSNormBackward);
    m.def("rope", &wallx_cuda_rope::Rope);
    m.def("rope_inplace", &wallx_cuda_rope::RopeInplace);
    m.def("rope_inplace_pack", &wallx_cuda_rope::RopeInplacePack);
    m.def("rope_bwd", &wallx_cuda_rope::RopeBackward);
    m.def("m_rope", &wallx_cuda_m_rope::MRope);
    m.def("m_rope_inplace", &wallx_cuda_m_rope::MRopeInplace);
    m.def("m_rope_inplace_pack", &wallx_cuda_m_rope::MRopeInplacePack);
    m.def("m_rope_bwd", &wallx_cuda_m_rope::MRopeBackward);
    m.def("get_token_counts", &wallx_cuda_rot_pos::GetTokenCounts);
    m.def("rot_pos", &wallx_cuda_rot_pos::RotPosEmb);
    m.def("get_rope_index", &wallx_cuda_get_rope_index::GetRopeIndex);
    m.def("get_rope_index_getworkspace", &wallx_cuda_get_rope_index::GetRopeIndexGetWorkSpace);
    m.def("get_window_index", &wallx_cuda_window_index::GetWindowIndex);
    m.def("get_totals", &wallx_cuda_window_index::GetTotals);
    m.def("permute", &wallx_cuda_permute::MoePermuteTopKOp);
    m.def("unpermute", &wallx_cuda_permute::MoeRecoverTopKOp);
    m.def("unpermute_bwd", &wallx_cuda_permute::MoeRecoverTopKBwdOp);
    m.def("cub_sort_pair_get_storage_bytes", &wallx_cuda_permute::CubSortPairGetStorageBytes);
}
