"""JIT-compiled CUDA kernels for wall_x ops (Level 2 backend).

Auto-generated by scripts/extract_cuda_kernels.py.
Do not edit manually.
"""

import os
from pathlib import Path

_module = None
_dir = Path(__file__).parent / "csrc"


def load():
    """Load the compiled CUDA extension module. Compiled on first call."""
    global _module
    if _module is not None:
        return _module

    from torch.utils.cpp_extension import load as _load

    _module = _load(
        name="wallx_ops",
        sources=[str(_dir / "binding.cu")],
        extra_include_paths=[str(_dir / "common")],
        extra_cuda_cflags=["-O3", "--use_fast_math"],
        verbose=os.environ.get("WALLX_OPS_VERBOSE", "0") == "1",
    )
    return _module


def is_available() -> bool:
    """Check if CUDA kernels can be compiled."""
    try:
        import torch

        return torch.cuda.is_available()
    except Exception:
        return False
