"""Auto-generated CUDA kernel wrappers with autograd support.

Generated by scripts/extract_cuda_kernels.py from internal CUDA wrappers.
Do not edit manually.
"""

import torch
from torch.autograd import Function


def _m():
    """Get the JIT-compiled CUDA extension module."""
    from wall_x.model.core.ops._cuda_ext import load

    return load()


def _get_sm_count():
    """Cache SM count for the current GPU."""
    if not hasattr(_get_sm_count, "_count"):
        _get_sm_count._count = torch.cuda.get_device_properties(
            torch.cuda.current_device()
        ).multi_processor_count
    return _get_sm_count._count


class _RmsnormFunction(torch.autograd.Function):
    @staticmethod
    def forward(ctx, input, weight, epsilon):
        output = torch.empty_like(input)
        _m().rmsnorm(output, input, weight, epsilon)
        ctx.save_for_backward(input, weight)
        ctx.epsilon = epsilon
        return output

    @staticmethod
    def backward(ctx, grad_output):
        input, weight = ctx.saved_tensors
        epsilon = ctx.epsilon
        hidden_size = weight.numel()
        num_tokens = input.numel() // hidden_size

        dx = torch.empty_like(input)
        dw_float = torch.empty(hidden_size, dtype=torch.float32, device=input.device)

        # Pre-allocate partial_dw buffer: [num_blocks, hidden_size]
        sm_count = _get_sm_count()
        num_blocks = min(sm_count, num_tokens)
        partial_dw = torch.empty(
            num_blocks, hidden_size, dtype=torch.float32, device=input.device
        )

        _m().rmsnorm_backward(
            dx, dw_float, partial_dw, grad_output, input, weight, epsilon
        )

        dw = dw_float.to(weight.dtype)
        return dx, dw, None


class Rmsnorm:
    def __init__(self):
        pass

    def __call__(self, input, weight, epsilon, inference=False):
        if inference:
            output = torch.empty_like(input)
            self.lib.rmsnorm(output, input, weight, epsilon)
            return output
        return _RmsnormFunction.apply(input, weight, epsilon)


class _RopeFunction(Function):
    @staticmethod
    def forward(
        ctx,
        q,
        k,
        cos,
        sin,
        interleave,
        fwd_kernel=None,
        bwd_kernel=None,
    ):
        q_embed = torch.empty_like(q)
        k_embed = torch.empty_like(k)
        ctx.save_for_backward(q, k, cos, sin)
        ctx.interleave = interleave
        ctx.bwd_kernel = bwd_kernel
        fwd_kernel(q, k, q_embed, k_embed, cos, sin, interleave)
        return q_embed, k_embed

    @staticmethod
    def backward(ctx, grad_q_embed, grad_k_embed):
        if grad_q_embed.stride(-1) != 1:
            grad_q_embed = grad_q_embed.contiguous()
        if grad_k_embed.stride(-1) != 1:
            grad_k_embed = grad_k_embed.contiguous()
        q, k, cos, sin = ctx.saved_tensors
        interleave = ctx.interleave
        bwd_kernel = ctx.bwd_kernel
        grad_q = torch.empty_like(q)
        grad_k = torch.empty_like(k)

        bwd_kernel(
            grad_q_embed,
            grad_k_embed,
            grad_q,  # output
            grad_k,  # output
            cos,
            sin,
            interleave,
        )

        return grad_q, grad_k, None, None, None, None, None


class Rope:
    def __init__(self):
        pass
        self.fwd_kernel = _m().rope
        self.inplace_kernel = _m().rope_inplace
        self.pack_kernel = _m().rope_inplace_pack
        self.bwd_kernel = _m().rope_bwd

    def pack(self, qkv, q_num_heads, kv_num_heads, cos, sin, interleave=False):
        """Apply RoPE to the q/k parts of packed qkv in place. Returns nothing.

        Split/view/offset calculations are done on the C++ side. Callers consume qkv through the paired
        flash_attn pack interface without splitting q/k/v in Python.

        Args:
            qkv:          [seq_len, q_dim + 2*kv_dim]
            q_num_heads:  number of query heads
            kv_num_heads: number of key/value heads
            cos, sin:     rotary position encoding [1, seq_len, head_dim/2]
            interleave:   whether to use interleaved RoPE
        """
        self.pack_kernel(qkv, cos, sin, q_num_heads, kv_num_heads, interleave)

    def __call__(self, q, k, cos, sin, interleave=False, inference=False):
        if inference:
            self.inplace_kernel(q, k, cos, sin, interleave)
            return q, k

        return _RopeFunction.apply(
            q,
            k,
            cos,
            sin,
            interleave,
            self.fwd_kernel,
            self.bwd_kernel,
        )


class _MRopeFunction(Function):
    @staticmethod
    def forward(
        ctx,
        q,
        k,
        cos,
        sin,
        mrope_section,
        fwd_kernel=None,
        bwd_kernel=None,
    ):
        first = mrope_section[0]
        second = mrope_section[1]
        ctx.save_for_backward(q, k, cos, sin)
        ctx.mrope_section = mrope_section
        ctx.bwd_kernel = bwd_kernel
        q_embed = torch.empty_like(q)
        k_embed = torch.empty_like(k)
        fwd_kernel(q, k, q_embed, k_embed, cos, sin, first, second)
        return q_embed, k_embed

    @staticmethod
    def backward(ctx, grad_q_embed, grad_k_embed):
        if grad_q_embed.stride(-1) != 1:
            grad_q_embed = grad_q_embed.contiguous()
        if grad_k_embed.stride(-1) != 1:
            grad_k_embed = grad_k_embed.contiguous()
        q, k, cos, sin = ctx.saved_tensors
        mrope_section = ctx.mrope_section
        bwd_kernel = ctx.bwd_kernel
        grad_q = torch.empty_like(q)
        grad_k = torch.empty_like(k)
        first = mrope_section[0]
        second = mrope_section[1]

        bwd_kernel(
            grad_q_embed,
            grad_k_embed,
            grad_q,  # output
            grad_k,  # output
            cos,
            sin,
            first,
            second,
        )

        return grad_q, grad_k, None, None, None, None, None


class MRope:
    def __init__(self):
        pass
        self.fwd_kernel = _m().m_rope
        self.inplace_kernel = _m().m_rope_inplace
        self.pack_kernel = _m().m_rope_inplace_pack
        self.bwd_kernel = _m().m_rope_bwd

    def pack(self, qkv, q_num_heads, kv_num_heads, cos, sin, mrope_section):
        """Apply M-RoPE to the q/k parts of packed qkv in place. Returns nothing. Supports GQA.

        Split/view/offset calculations are done on the C++ side. qkv must be 3D: [bz, seq_len, q_dim+2*kv_dim].

        Args:
            qkv:          [bz, seq_len, q_dim + 2*kv_dim]
            q_num_heads:  number of query heads
            kv_num_heads: number of key/value heads
            cos, sin:     rotary position encoding [3, bz, seq_len, head_dim/2]
            mrope_section: (first, second) M-RoPE section parameters
        """
        self.pack_kernel(
            qkv, cos, sin, q_num_heads, kv_num_heads, mrope_section[0], mrope_section[1]
        )

    def __call__(self, q, k, cos, sin, mrope_section, inference=False):
        if inference:
            first = mrope_section[0]
            second = mrope_section[1]
            self.inplace_kernel(q, k, cos, sin, first, second)
            return q, k

        return _MRopeFunction.apply(
            q,
            k,
            cos,
            sin,
            mrope_section,
            self.fwd_kernel,
            self.bwd_kernel,
        )


class RotPos:
    def __init__(self):
        pass

    def __call__(self, inv_freq, grid_thw, spatial_merge_size):
        assert (
            inv_freq.dtype == torch.float32
        ), f"Expected float32, got {inv_freq.dtype}"
        get_token_counts_kernel = _m().get_token_counts
        rot_pos_kernel = _m().rot_pos

        num_grids = grid_thw.size(0)
        token_counts = torch.zeros(
            (num_grids), dtype=grid_thw.dtype, device=grid_thw.device
        )

        get_token_counts_kernel(grid_thw, token_counts, spatial_merge_size)
        cumsum_tokens = torch.cat(
            [
                torch.zeros(1, dtype=token_counts.dtype, device=token_counts.device),
                token_counts.cumsum(dim=0),
            ],
            dim=0,
        ).to(grid_thw.dtype)

        output = torch.empty(
            (cumsum_tokens[-1].item(), inv_freq.size(0) * 2),
            dtype=torch.float,
            device=inv_freq.device,
        )
        rot_pos_kernel(inv_freq, grid_thw, output, cumsum_tokens, spatial_merge_size)

        return output


class GetRopeIndex:
    def __init__(self):
        pass

    def __call__(
        self,
        input_ids,
        image_grid_thw,
        video_grid_thw,
        second_per_grid_ts,
        attention_mask,
        spatial_merge_size,
        image_token_id,
        video_token_id,
        vision_start_token_id,
        tokens_per_second,
    ):
        get_workspace = _m().get_rope_index_getworkspace
        get_rope_index_kernel = _m().get_rope_index
        work_space_size = get_workspace(input_ids, image_grid_thw, video_grid_thw)

        workspace = torch.empty(
            work_space_size, dtype=torch.uint8, device=input_ids.device
        )
        batch_size = input_ids.size(0)
        seq_len = input_ids.size(1)
        position_ids = torch.empty(
            (3, batch_size, seq_len), dtype=torch.int64, device=input_ids.device
        )
        mrope_deltas = torch.empty(
            (batch_size, 1), dtype=torch.int64, device=input_ids.device
        )
        get_rope_index_kernel(
            input_ids,
            image_grid_thw,
            video_grid_thw,
            second_per_grid_ts,
            attention_mask,
            position_ids,
            mrope_deltas,
            workspace,
            spatial_merge_size,
            image_token_id,
            video_token_id,
            vision_start_token_id,
            tokens_per_second,
        )

        return position_ids, mrope_deltas


get_window_index_kernel = _m().get_window_index
get_totals_kernel = _m().get_totals


def get_window_index_cuda(
    grid_thw, window_size, spatial_merge_size, patch_size, spatial_merge_unit=1
):

    if grid_thw.size(0) == 0:
        return (
            torch.empty(0, dtype=grid_thw.dtype, device=grid_thw.device),
            torch.zeros(1, dtype=grid_thw.dtype, device=grid_thw.device),
        )

    vit_merger_window_size = window_size // spatial_merge_size // patch_size

    grid_info_tensor = torch.empty(
        (grid_thw.size(0), 6), dtype=grid_thw.dtype, device=grid_thw.device
    )
    global_totals_tensor = torch.zeros(
        (2), dtype=grid_thw.dtype, device=grid_thw.device
    )
    get_totals_kernel(
        grid_thw,
        grid_info_tensor,
        global_totals_tensor,
        spatial_merge_size,
        vit_merger_window_size,
    )
    total_elements = global_totals_tensor[0].item()
    total_windows = global_totals_tensor[1].item()
    if total_elements == 0 or total_windows == 0:
        return (
            torch.empty(0, dtype=grid_thw.dtype, device=grid_thw.device),
            torch.zeros(1, dtype=grid_thw.dtype, device=grid_thw.device),
        )

    window_indices = torch.empty(
        total_elements, dtype=grid_thw.dtype, device=grid_thw.device
    )
    cu_window_seqlens = torch.empty(
        (total_windows + 1), dtype=grid_thw.dtype, device=grid_thw.device
    )
    window_counts_tensor = torch.empty(
        (total_windows), dtype=grid_thw.dtype, device=grid_thw.device
    )

    max_grid_t = grid_thw[:, 0].max().item()
    get_window_index_kernel(
        grid_thw,
        grid_info_tensor,
        window_indices,
        cu_window_seqlens,
        window_counts_tensor,
        max_grid_t,
        spatial_merge_size,
        vit_merger_window_size,
        patch_size,
        spatial_merge_unit,
    )

    return window_indices, cu_window_seqlens


################################################################################################
##
## PermuteMoE topK
##
################################################################################################


class PermuteMoE_topK(torch.autograd.Function):

    dtype = None
    max_expanded_token_num = 0

    @staticmethod
    def forward(
        ctx,
        input_act: torch.Tensor,
        indices: torch.Tensor,
        num_out_tokens: int,
        max_token_num: int,
    ):
        """
        indices: for topK=1, indices in a 1-d tensor of shape [num_tokens],
                 otherwise, it's a 2-d tensor of shape [num_tokens, topK]
        """
        if not input_act.numel():
            return input_act, None

        # For top1 case, view the indices as 2D tensor to unify the shape for topk>=2 cases.
        if indices.dim() == 1:
            indices = indices.view(-1, 1)

        # Device check
        if input_act.is_cpu:
            raise RuntimeError(
                "[Error] The input `input_act` of permute_topK op is on the device: CPU!"
            )

        # Data type check
        if indices.dtype != torch.int32:
            indices = indices.to(torch.int32)

        # Contiguous check
        if not input_act.is_contiguous():
            input_act = input_act.contiguous()
        if not indices.is_contiguous():
            indices = indices.contiguous()

        num_topK = indices.size(1)

        input_max_expanded_token_num = max(max_token_num, input_act.size(0)) * num_topK
        if PermuteMoE_topK.max_expanded_token_num < input_max_expanded_token_num:
            PermuteMoE_topK.max_expanded_token_num = input_max_expanded_token_num

        permute_kernel = _m().permute
        sorted_indices = torch.empty(
            PermuteMoE_topK.max_expanded_token_num,
            dtype=torch.int32,
            device=input_act.device,
        )
        row_id = torch.arange(
            PermuteMoE_topK.max_expanded_token_num,
            dtype=torch.int32,
            device=input_act.device,
        )
        sorted_row_id = torch.empty(
            PermuteMoE_topK.max_expanded_token_num,
            dtype=torch.int32,
            device=input_act.device,
        )
        get_storage_bytes_kernel = _m().cub_sort_pair_get_storage_bytes
        temp_storage_bytes = get_storage_bytes_kernel(
            PermuteMoE_topK.max_expanded_token_num
        )
        temp_storage = torch.empty(
            temp_storage_bytes, dtype=torch.int8, device=input_act.device
        )
        num_out = (
            num_out_tokens if (num_out_tokens > 0) else (indices.size(0) * num_topK)
        )
        permuted_output = torch.empty(
            (num_out, input_act.size(1)), dtype=input_act.dtype, device=input_act.device
        )
        row_id_map = torch.empty(
            (indices.size(0) * num_topK), dtype=torch.int32, device=input_act.device
        )
        permute_kernel(
            input_act,
            indices,
            sorted_indices,
            row_id,
            sorted_row_id,
            temp_storage,
            permuted_output,
            row_id_map,
            num_out_tokens,
            PermuteMoE_topK.max_expanded_token_num,
        )

        ctx.row_id_map = row_id_map
        ctx.num_tokens = indices.size(0)
        ctx.num_topK = num_topK

        return permuted_output, row_id_map

    @staticmethod
    def backward(ctx, permuted_act_grad, _):
        if not permuted_act_grad.numel():
            return permuted_act_grad, None, None, None

        unpermute_kernel = _m().unpermute
        if not permuted_act_grad.is_contiguous():
            permuted_act_grad = permuted_act_grad.contiguous()

        row_id_map = ctx.row_id_map
        num_tokens = ctx.num_tokens
        num_topK = ctx.num_topK
        num_cols = permuted_act_grad.size(1)
        unpermuted_output = torch.empty(
            (num_tokens, num_cols),
            dtype=permuted_act_grad.dtype,
            device=permuted_act_grad.device,
        )
        unpermute_kernel(
            permuted_act_grad, row_id_map, None, unpermuted_output, num_tokens, num_topK
        )

        return unpermuted_output, None, None, None


################################################################################################
##
## UnpermuteMoE topK
##
################################################################################################


class UnpermuteMoE_topK(torch.autograd.Function):

    @staticmethod
    def forward(
        ctx,
        input_act: torch.Tensor,
        row_id_map: torch.Tensor,
        probs: torch.Tensor = None,
    ):

        if not input_act.numel():
            ctx.probs = probs
            return input_act

        # Device check
        if input_act.is_cpu:
            raise RuntimeError(
                "[Error] The input `input_act` of unpermute_topK op is on the device: CPU!"
            )
        if row_id_map.is_cpu:
            row_id_map = row_id_map.cuda()
        if probs is not None and probs.is_cpu:
            probs = probs.cuda()

        # Shape check
        if probs is not None and row_id_map.size(0) != probs.size(0) * probs.size(1):
            raise RuntimeError(
                f"[Error] unpermute_topK op input `probs` shape mismatch! "
                f"Expect {row_id_map.size(0)}, but got {probs.size(0) * probs.size(1)}."
            )

        # Data type check
        if row_id_map.dtype != torch.int32:
            row_id_map = row_id_map.to(torch.int32)
        if probs is not None and probs.dtype != torch.float32:
            probs = probs.to(torch.float32)

        # Contiguous check
        if not input_act.is_contiguous():
            input_act = input_act.contiguous()
        if not row_id_map.is_contiguous():
            row_id_map = row_id_map.contiguous()
        if probs is not None and not probs.is_contiguous():
            probs = probs.contiguous()

        num_tokens = probs.size(0) if probs is not None else input_act.size(0)
        num_topK = probs.size(1) if probs is not None else 1
        unpermute_kernel = _m().unpermute
        num_cols = input_act.size(1)
        unpermuted_output = torch.empty(
            (num_tokens, num_cols), dtype=input_act.dtype, device=input_act.device
        )
        unpermute_kernel(
            input_act, row_id_map, probs, unpermuted_output, num_tokens, num_topK
        )

        ctx.save_for_backward(input_act, row_id_map, probs)

        return unpermuted_output

    @staticmethod
    def backward(ctx, unpermuted_act_grad):

        if not unpermuted_act_grad.numel():
            return unpermuted_act_grad, None, ctx.probs

        if not unpermuted_act_grad.is_contiguous():
            unpermuted_act_grad = unpermuted_act_grad.contiguous()

        input_act, row_id_map, probs = ctx.saved_tensors

        act_grad = None
        unpermute_bwd_kernel = _m().unpermute_bwd
        if ctx.needs_input_grad[0]:
            num_cols = unpermuted_act_grad.size(1)
            act_grad = torch.empty(
                (input_act.size(0), num_cols),
                dtype=unpermuted_act_grad.dtype,
                device=unpermuted_act_grad.device,
            )
            prob_grad = torch.empty(
                (probs.size(0), probs.size(1)),
                dtype=torch.float32,
                device=unpermuted_act_grad.device,
            )
            unpermute_bwd_kernel(
                unpermuted_act_grad, input_act, row_id_map, probs, act_grad, prob_grad
            )

        if not ctx.needs_input_grad[2]:
            prob_grad = None

        return act_grad, None, prob_grad


def permute_kernel(input_act, indices, num_out_tokens=None, max_token_num=0):
    num_out_tokens = 0 if num_out_tokens is None else num_out_tokens
    return PermuteMoE_topK.apply(input_act, indices, num_out_tokens, max_token_num)


def unpermute_kernel(input_act, row_id_map, probs=None):
    return UnpermuteMoE_topK.apply(input_act, row_id_map, probs)
